apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
spec:
  rules:
    - host: preprod.user-portail.ip-ddns.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: users-front
                port:
                  number: {{ .Values.usersFront.servicePort }}