apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-front
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-front
  template:
    metadata:
      labels:
        app: users-front
    spec:
      containers:
        - name: users-front
          image: {{ printf "%s:%s" .Values.usersFront.image .Values.usersFront.tag }}
          ports:
            - containerPort: {{ .Values.usersFront.containerPort }}