apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: {{ .Values.usersBack.servicePort }}
      targetPort: {{ .Values.usersBack.containerPort }}
  type: ClusterIP
