usersBack:
  image: awsfox92/soutenance-project-demo
  tag: "0.0.13"
  servicePort: 8080
  containerPort: 8080

usersFront:
  image: awsfox92/soutenance-ui
  tag: "0.0.14"
  servicePort: 80
  containerPort: 80

namespace: prod

ingress:
  enabled: true
  certificateArn: arn:aws:acm:us-east-1:828776881371:certificate/fa052d8a-f038-41b9-aef0-0ce5fc111fff

dd:
  env: prod