usersBack:
  image: awsfox92/soutenance-project-demo
  tag: "0.0.6"
  servicePort: 8080
  containerPort: 8080

usersFront:
  image: awsfox92/soutenance-ui
  tag: "0.0.6"
  servicePort: 80
  containerPort: 80

namespace: preprod